before_script:
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - gem install dpl

deploy-staging:
  type: deploy
  script:
    - dpl --provider=heroku --app=flush-gordon --api-key=$HEROKU_PRODUCTION_API
  only:
    - master
